Repository boutproject/xBOUT, pull requests merged in 2019-12, with the labels that each got.

#55 Fix test against collect
  .travis.yml
  pytest.ini
  xbout/boutdataarray.py
  xbout/boutdataset.py
  xbout/geometries.py
  xbout/load.py
  xbout/tests/test_against_collect.py
  xbout/tests/test_animate.py
  xbout/tests/test_grid.py
  xbout/tests/test_load.py
  xbout/utils.py
Labels: testing

#50 Plot poloidal plane with contour, contourf or pcolormesh
  examples/plot_grid.py
  xbout/boutdataarray.py
  xbout/plotting/plotfuncs.py
  xbout/plotting/utils.py
Labels: enhancement

#65 Use tmpdir_factory in test_open_grid_extra_dims
  xbout/tests/test_grid.py
Labels: testing

#70 Test and update minimum supported versions
  .travis.yml
  docs/index.rst
  requirements.txt
  setup.py
  xbout/plotting/animate.py
Labels: testing

#51 Enable reading of single, squashed output files
  xbout/load.py
  xbout/tests/test_load.py
Labels: enhancement

#78 Make xbout install plotting functions
  setup.py
Labels: bugfix

#80 Fix animate_list blank figures
  xbout/boutdataset.py
  xbout/plotting/animate.py
Labels: bugfix

#77 Fix slicing in _decompose_regions
  xbout/plotting/utils.py
Labels: bugfix

#87 Close netCDF files in collect
  xbout/load.py
Labels: bugfix

#88 Allow passing custom titles to animate_list
  xbout/boutdataset.py
  xbout/tests/test_animate.py
Labels: bugfix

#92 Document all optional arguments in docstrings of animation methods/functions
  xbout/boutdataarray.py
  xbout/plotting/animate.py
Labels: documentation

#93 More robust handling of 'chunks' when opening grid files
  xbout/load.py
  xbout/tests/test_grid.py
Labels: bugfix
